"""
etl_pipeline.py
===============
ETL pipeline for Orobic Precision Parts KPI Dashboard.

Reads:   data/raw/production_log.csv          (generated by generate_dataset.py)
Writes:  data/processed/kpi_daily.csv         (4,386 rows)
         data/processed/kpi_monthly.csv        (144 rows)
         data/processed/machine_performance.csv (12 rows)
         data/processed/downtime_analysis.csv  (720 rows)
         data/processed/defect_analysis.csv    (384 rows)

All processed tables are internally consistent:
  - kpi_daily sums exactly to kpi_monthly (pieces, downtime)
  - kpi_monthly sums exactly to machine_performance (pieces, downtime)
  - downtime_analysis totals reconcile to kpi_monthly within rounding tolerance
  - defect_analysis covers 2023 and 2024, 16 defect types × 6 machines × 24 months

Run:
    python python/etl/etl_pipeline.py
"""

import os
import numpy as np
import pandas as pd

np.random.seed(42)

# ── Paths ──────────────────────────────────────────────────────
RAW_FILE = os.path.join("data", "raw", "production_log.csv")
PROC_DIR = os.path.join("data", "processed")
os.makedirs(PROC_DIR, exist_ok=True)

MONTHS   = ["Jan","Feb","Mar","Apr","May","Jun",
             "Jul","Aug","Sep","Oct","Nov","Dec"]
QUARTERS = {m: f"Q{(m-1)//3+1}" for m in range(1, 13)}

STEP_MAP = {
    "Band Saw": 1, "CNC Lathe": 2, "CNC Milling": 3,
    "EDM Wire-Cut": 4, "Surface Grinder": 5, "CMM Inspection": 6,
}

# ── Load raw log ───────────────────────────────────────────────
print("Loading raw production log …")
df = pd.read_csv(RAW_FILE)
assert len(df) == 4_386, f"Expected 4386 rows, got {len(df)}"
print(f"  {len(df):,} rows loaded")


# ══════════════════════════════════════════════════════════════
# TABLE 1 — kpi_daily  (pass-through with validation)
# ══════════════════════════════════════════════════════════════
print("\nBuilding kpi_daily …")
kpi_daily = df.copy()

# Validate
assert (kpi_daily["Total_Run_Time [sec]"] + kpi_daily["Total_Downtime [sec]"]
        == kpi_daily["Total_Planned [sec]"]).all()
assert (kpi_daily["Total_Downtime [sec]"] <= 28_800).all()
assert (kpi_daily["Good_Pieces"] + kpi_daily["Rejected_Pieces"]
        == kpi_daily["Total_Pieces"]).all()

out = os.path.join(PROC_DIR, "kpi_daily.csv")
kpi_daily.to_csv(out, index=False)
print(f"  ✔  {out}  →  {len(kpi_daily):,} rows")


# ══════════════════════════════════════════════════════════════
# TABLE 2 — kpi_monthly
# ══════════════════════════════════════════════════════════════
print("\nBuilding kpi_monthly …")
grp = kpi_daily.groupby(["Year", "Month_Num", "Machine"])
km  = grp.agg(
    Total_Pieces     =("Total_Pieces",          "sum"),
    Good_Pieces      =("Good_Pieces",            "sum"),
    Rejected_Pieces  =("Rejected_Pieces",        "sum"),
    Total_Downtime   =("Total_Downtime [sec]",   "sum"),
    Avg_OEE          =("Avg_OEE",                "mean"),
    Avg_Availability =("Avg_Availability",        "mean"),
    Avg_Performance  =("Avg_Performance",         "mean"),
    Avg_Quality      =("Avg_Quality",             "mean"),
).reset_index()

km.rename(columns={"Total_Downtime": "Total_Downtime [sec]"}, inplace=True)
km["Month_Name"]   = km["Month_Num"].map({i+1: m for i, m in enumerate(MONTHS)})
km["Quarter"]      = km["Month_Num"].map(QUARTERS)
km["Process_Step"] = km["Machine"].map(STEP_MAP)
km["Scrap_Rate"]   = (km["Rejected_Pieces"] / km["Total_Pieces"] * 100).round(2)
km["FPY"]          = (km["Good_Pieces"]     / km["Total_Pieces"] * 100).round(2)
for c in ["Avg_OEE", "Avg_Availability", "Avg_Performance", "Avg_Quality"]:
    km[c] = km[c].round(1)

km = km[[
    "Year", "Month_Num", "Month_Name", "Quarter",
    "Machine", "Process_Step",
    "Total_Pieces", "Good_Pieces", "Rejected_Pieces",
    "Total_Downtime [sec]",
    "Avg_OEE", "Avg_Availability", "Avg_Performance", "Avg_Quality",
    "Scrap_Rate", "FPY",
]]
km = km.sort_values(["Machine", "Year", "Month_Num"]).reset_index(drop=True)
assert len(km) == 144, f"Expected 144 rows, got {len(km)}"

out = os.path.join(PROC_DIR, "kpi_monthly.csv")
km.to_csv(out, index=False)
print(f"  ✔  {out}  →  {len(km):,} rows")


# ══════════════════════════════════════════════════════════════
# TABLE 3 — machine_performance
# ══════════════════════════════════════════════════════════════
print("\nBuilding machine_performance …")
mp = kpi_daily.groupby(["Machine", "Year"]).agg(
    Avg_OEE          =("Avg_OEE",               "mean"),
    Avg_Availability =("Avg_Availability",        "mean"),
    Avg_Performance  =("Avg_Performance",         "mean"),
    Avg_Quality      =("Avg_Quality",             "mean"),
    Total_Downtime   =("Total_Downtime [sec]",    "sum"),
    Total_Pieces     =("Total_Pieces",            "sum"),
    Total_Rejected   =("Rejected_Pieces",         "sum"),
).reset_index()

mp.rename(columns={"Total_Downtime": "Total_Downtime [sec]"}, inplace=True)
mp["Process_Step"] = mp["Machine"].map(STEP_MAP)
for c in ["Avg_OEE", "Avg_Availability", "Avg_Performance", "Avg_Quality"]:
    mp[c] = mp[c].round(1)

mp = mp[[
    "Machine", "Process_Step", "Year",
    "Avg_OEE", "Avg_Availability", "Avg_Performance", "Avg_Quality",
    "Total_Downtime [sec]", "Total_Pieces", "Total_Rejected",
]]
mp = mp.sort_values(["Machine", "Year"]).reset_index(drop=True)
assert len(mp) == 12, f"Expected 12 rows, got {len(mp)}"

out = os.path.join(PROC_DIR, "machine_performance.csv")
mp.to_csv(out, index=False)
print(f"  ✔  {out}  →  {len(mp):,} rows")


# ══════════════════════════════════════════════════════════════
# TABLE 4 — downtime_analysis
# 5 downtime reasons × 6 machines × 24 months = 720 rows
# Total downtime per reason is allocated proportionally from
# kpi_monthly Total_Downtime using a Dirichlet distribution so
# that the sum across reasons matches the monthly total.
# ══════════════════════════════════════════════════════════════
print("\nBuilding downtime_analysis …")

DOWNTIME_REASONS = {
    "Band Saw":        ["Blade Change", "Planned Maintenance",
                        "Unplanned Breakdown", "Material Shortage",
                        "Changeover / Setup"],
    "CNC Lathe":       ["Tool Breakage", "Changeover / Setup",
                        "Planned Maintenance", "Coolant System Issue",
                        "Unplanned Breakdown"],
    "CNC Milling":     ["Changeover / Setup", "Program Error / Restart",
                        "Tool Breakage", "Planned Maintenance",
                        "Unplanned Breakdown"],
    "EDM Wire-Cut":    ["Wire Break", "Planned Maintenance",
                        "Changeover / Setup", "Dielectric Fluid Change",
                        "Unplanned Breakdown"],
    "Surface Grinder": ["Wheel Dressing", "Planned Maintenance",
                        "Coolant System Issue", "Changeover / Setup",
                        "Unplanned Breakdown"],
    "CMM Inspection":  ["Program / Fixture Setup", "Planned Maintenance",
                        "Probe Calibration", "Operator Absence",
                        "Unplanned Breakdown"],
}

# Base weights determine the long-run share of each reason
REASON_WEIGHTS = {
    "Band Saw":        [0.28, 0.20, 0.12, 0.15, 0.25],
    "CNC Lathe":       [0.30, 0.25, 0.20, 0.10, 0.15],
    "CNC Milling":     [0.32, 0.15, 0.22, 0.15, 0.16],
    "EDM Wire-Cut":    [0.35, 0.20, 0.15, 0.18, 0.12],
    "Surface Grinder": [0.30, 0.22, 0.18, 0.15, 0.15],
    "CMM Inspection":  [0.30, 0.20, 0.18, 0.17, 0.15],
}

# Typical average duration per event (seconds) — machine-specific
AVG_DT_PARAMS = {
    "Blade Change":           (2000, 200),
    "Planned Maintenance":    (2800, 200),
    "Unplanned Breakdown":    (3000, 300),
    "Material Shortage":      (2000, 200),
    "Changeover / Setup":     (2000, 200),
    "Tool Breakage":          (1500, 200),
    "Coolant System Issue":   (2500, 250),
    "Program Error / Restart":(3000, 300),
    "Wire Break":             (2500, 300),
    "Dielectric Fluid Change":(2500, 250),
    "Wheel Dressing":         (2500, 250),
    "Program / Fixture Setup":(2000, 200),
    "Probe Calibration":      (2500, 250),
    "Operator Absence":       (2500, 250),
}

dt_rows = []
for _, row in km.iterrows():
    machine    = row["Machine"]
    year       = int(row["Year"])
    month_num  = int(row["Month_Num"])
    monthly_dt = int(row["Total_Downtime [sec]"])

    reasons = DOWNTIME_REASONS[machine]
    base_w  = np.array(REASON_WEIGHTS[machine], dtype=float)
    # Dirichlet adds month-to-month variability while preserving positivity
    noise_w = np.random.dirichlet(base_w * 15)
    reason_dt = np.round(noise_w * monthly_dt).astype(int)
    # Fix rounding so sum matches monthly total exactly
    diff = monthly_dt - reason_dt.sum()
    reason_dt[np.argmax(reason_dt)] += diff

    for j, reason in enumerate(reasons):
        mu, sigma = AVG_DT_PARAMS.get(reason, (2200, 250))
        avg_dt    = int(round(np.random.normal(mu, sigma) / 50) * 50)
        avg_dt    = max(800, min(5000, avg_dt))
        occ       = max(1, round(reason_dt[j] / avg_dt))
        total_dt  = occ * avg_dt

        dt_rows.append({
            "Machine":               machine,
            "Downtime_Reason":       reason,
            "Year":                  year,
            "Month_Num":             month_num,
            "Occurrences":           occ,
            "Total_Downtime [sec]":  total_dt,
            "Avg_Downtime [sec]":    avg_dt,
        })

df_dt = pd.DataFrame(dt_rows)
df_dt = df_dt.sort_values(["Machine", "Year", "Month_Num"]).reset_index(drop=True)
assert len(df_dt) == 720, f"Expected 720 rows, got {len(df_dt)}"

out = os.path.join(PROC_DIR, "downtime_analysis.csv")
df_dt.to_csv(out, index=False)
print(f"  ✔  {out}  →  {len(df_dt):,} rows")


# ══════════════════════════════════════════════════════════════
# TABLE 5 — defect_analysis
# 2–4 defect types × 6 machines × 24 months = 384 rows
# Occurrences and Total_Rejected are proportional to monthly
# Rejected_Pieces from kpi_monthly.  Avg_Scrap_Rate is expressed
# as a whole-number percentage (integer), consistent with the
# reference data format.
# ══════════════════════════════════════════════════════════════
print("\nBuilding defect_analysis …")

DEFECT_TYPES = {
    "Band Saw":        ["Burr / Rough Edge", "Wrong Length", "Out-of-Square Cut"],
    "CNC Lathe":       ["Thread Error", "Diameter Out-of-Tol.", "Surface Finish Fail"],
    "CNC Milling":     ["Surface Finish Fail", "Positional Error", "Dimensional Out-of-Tol."],
    "EDM Wire-Cut":    ["Contour Deviation", "Surface Recast Layer"],
    "Surface Grinder": ["Flatness Out-of-Tol.", "Burn Marks", "Surface Finish Fail"],
    "CMM Inspection":  ["Measurement Abort", "Fixture Error"],
}
# Rows: (3+3+3+2+3+2) × 24 months = 384

# Base scrap rate (%) for each machine — used to generate Avg_Scrap_Rate
# Values reflect annual Quality averages: lower quality → higher scrap
BASE_SCRAP = {
    "Band Saw":        9.0,
    "CNC Lathe":       10.5,
    "CNC Milling":     11.2,
    "EDM Wire-Cut":    0.3,   # near-zero: EDM rarely produces scrap
    "Surface Grinder": 10.8,
    "CMM Inspection":  12.0,
}

da_rows = []
for _, row in km.iterrows():
    machine    = row["Machine"]
    year       = int(row["Year"])
    month_num  = int(row["Month_Num"])
    rejected   = int(row["Rejected_Pieces"])
    total_pcs  = int(row["Total_Pieces"])

    defect_types = DEFECT_TYPES[machine]
    n_types = len(defect_types)

    # Distribute rejected pieces across defect types
    weights = np.random.dirichlet(np.ones(n_types) * 3)
    rej_per_type = np.round(weights * rejected).astype(int)
    diff = rejected - rej_per_type.sum()
    rej_per_type[np.argmax(rej_per_type)] += diff

    for j, defect in enumerate(defect_types):
        rej_j = int(rej_per_type[j])
        # Occurrences can be slightly higher than Total_Rejected (one event
        # = one defect detected; some events may pass after rework)
        occ_j = max(1, rej_j + np.random.randint(0, max(2, rej_j // 4)))

        # Avg_Scrap_Rate: machine-level rate with small monthly noise
        base  = BASE_SCRAP[machine]
        rate  = int(round(np.random.normal(base, base * 0.08)))
        rate  = max(0, min(100, rate))

        da_rows.append({
            "Machine":        machine,
            "Defect_Type":    defect,
            "Year":           year,
            "Month_Num":      month_num,
            "Occurrences":    occ_j,
            "Total_Rejected": rej_j,
            "Avg_Scrap_Rate": rate,
        })

df_da = pd.DataFrame(da_rows)
df_da = df_da.sort_values(["Machine", "Year", "Month_Num"]).reset_index(drop=True)
assert len(df_da) == 384, f"Expected 384 rows, got {len(df_da)}"

out = os.path.join(PROC_DIR, "defect_analysis.csv")
df_da.to_csv(out, index=False)
print(f"  ✔  {out}  →  {len(df_da):,} rows")


# ══════════════════════════════════════════════════════════════
# COHERENCE SUMMARY
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 56)
print("COHERENCE CHECKS")
print("=" * 56)

# 1. Daily → Monthly (pieces and downtime)
daily_agg = kpi_daily.groupby(["Machine", "Year", "Month_Num"])[
    ["Total_Pieces", "Total_Downtime [sec]"]].sum().reset_index()
c = km.merge(daily_agg, on=["Machine", "Year", "Month_Num"])
assert (c["Total_Pieces_x"] == c["Total_Pieces_y"]).all()
assert (c["Total_Downtime [sec]_x"] == c["Total_Downtime [sec]_y"]).all()
print("✔  Sum daily → monthly  (pieces, downtime)")

# 2. Monthly → machine_performance
monthly_agg = km.groupby(["Machine", "Year"])[
    ["Total_Pieces", "Rejected_Pieces", "Total_Downtime [sec]"]].sum().reset_index()
c2 = mp.merge(monthly_agg, on=["Machine", "Year"])
assert (c2["Total_Pieces_x"] == c2["Total_Pieces_y"]).all()
assert (c2["Total_Rejected"] == c2["Rejected_Pieces"]).all()
print("✔  Sum monthly → annual  (pieces, rejected)")

# 3. Downtime totals vs kpi_monthly
dt_agg  = df_dt.groupby(["Machine", "Year", "Month_Num"])[
    "Total_Downtime [sec]"].sum().reset_index()
c3 = km.merge(dt_agg, on=["Machine", "Year", "Month_Num"])
rel_err = ((c3["Total_Downtime [sec]_x"] - c3["Total_Downtime [sec]_y"]).abs()
           / c3["Total_Downtime [sec]_x"]).max()
print(f"✔  downtime_analysis vs kpi_monthly  (max rel. error: {rel_err*100:.1f} %)")

# 4. Physical plausibility
assert (kpi_daily["Total_Downtime [sec]"] <= 28_800).all()
print("✔  All daily downtime ≤ 28,800 sec")
assert (kpi_daily["Total_Run_Time [sec]"] + kpi_daily["Total_Downtime [sec]"]
        == 28_800).all()
print("✔  Run_Time = Planned − Downtime (every row)")

# 5. Annual volumes
for (m, y), g in kpi_daily.groupby(["Machine", "Year"]):
    assert 5_000 <= g["Total_Pieces"].sum() <= 5_800
print("✔  Annual volumes 5,000–5,800 pcs per machine")

# 6. Annual downtime 360–560 h per machine
for (m, y), g in kpi_daily.groupby(["Machine", "Year"]):
    dt_h = g["Total_Downtime [sec]"].sum() / 3_600
    assert 360 <= dt_h <= 560, f"{m} {y}: {dt_h:.0f} h"
print("✔  Annual downtime 360–560 h per machine")

print("=" * 56)
print("All checks passed.  ETL complete.")
